#!/bin/sh
# Build an installable .apk from the APKBUILD, without abuild.
#
#   ./mkapk.sh [OUTDIR]
#
# abuild is the right tool for this and does much more than this script: it
# verifies checksums, resolves and installs build dependencies, strips binaries,
# scans for missing shared libraries, generates subpackages and signs the result.
# None of that is needed here - rpgm is noarch and installs a handful of scripts -
# so this exists for the case where installing abuild is not an option.
#
# The result is unsigned, so it installs with --allow-untrusted:
#
#   apk add --allow-untrusted rpgm-0.1.0-r0.apk
#
# Needs: python3, tar, gzip. To build a signed package, or anything with compiled
# code in it, use abuild instead - see README.md.

# pkgname, pkgver, pkgrel, package() and the rest are defined by the APKBUILD this
# sources, and srcdir/builddir are set here for it to read.
# shellcheck disable=SC2034,SC2154
set -eu

cd "$(dirname "$0")"
out=${1:-.}
[ -f APKBUILD ] || { echo "mkapk.sh: no APKBUILD here" >&2; exit 1; }
command -v python3 >/dev/null || { echo "mkapk.sh: python3 is required" >&2; exit 1; }

# The APKBUILD is a shell script, so the metadata and the packaging step come
# from the file itself rather than being repeated here. abuild would unpack the
# release tarball into $srcdir first; this builds the checkout it is sitting in,
# so both point at it.
srcdir=$PWD builddir=$PWD
# shellcheck disable=SC1091,SC2154 # sourced at run time; these come from it
. ./APKBUILD

pkgdir=$(mktemp -d)
staged=$pkgdir
trap 'rm -rf "$staged"' EXIT INT TERM
export pkgdir
package

apk=$out/$pkgname-$pkgver-r$pkgrel.apk
mkdir -p "$out"

python3 - "$pkgdir" "$apk" <<'PY' \
	"$pkgname" "$pkgver-r$pkgrel" "${pkgdesc:-}" "${url:-}" "${arch:-noarch}" \
	"${license:-}" "${depends:-}"
import gzip, hashlib, io, os, sys, tarfile, time

pkgdir, apkpath = sys.argv[1], sys.argv[2]
name, ver, desc, url, arch, lic, deps = sys.argv[3:10]


def add_tree(tf, root):
    """Every entry carries the SHA-1 pax record apk-tools looks for; without it
    apk refuses the package with 'file format is obsolete'."""
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for n in sorted(dirnames) + sorted(filenames):
            full = os.path.join(dirpath, n)
            rel = os.path.relpath(full, root)
            ti = tf.gettarinfo(full, rel)
            ti.uid = ti.gid = 0
            ti.uname = ti.gname = 'root'
            if ti.isreg():
                with open(full, 'rb') as f:
                    data = f.read()
                ti.pax_headers = {'APK-TOOLS.checksum.SHA1': hashlib.sha1(data).hexdigest()}
                tf.addfile(ti, io.BytesIO(data))
            elif ti.islnk() or ti.issym():
                ti.pax_headers = {
                    'APK-TOOLS.checksum.SHA1':
                        hashlib.sha1(ti.linkname.encode()).hexdigest()}
                tf.addfile(ti)
            else:
                tf.addfile(ti)


def segment(fill, cut):
    """One gzip member. apk reads the segments back to back, so every segment but
    the last has tar's end-of-archive blocks removed."""
    raw = io.BytesIO()
    with tarfile.open(fileobj=raw, mode='w', format=tarfile.PAX_FORMAT) as tf:
        fill(tf)
    body = raw.getvalue()
    if cut:
        while len(body) >= 512 and body[-512:] == b'\0' * 512:
            body = body[:-512]
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=9, mtime=0) as gz:
        gz.write(body)
    return buf.getvalue()


data = segment(lambda tf: add_tree(tf, pkgdir), cut=False)

size = 0
for dirpath, _, filenames in os.walk(pkgdir):
    for n in filenames:
        p = os.path.join(dirpath, n)
        if not os.path.islink(p):
            size += os.path.getsize(p)

info = [f'# Generated by mkapk.sh', f'pkgname = {name}', f'pkgver = {ver}']
if desc:
    info.append(f'pkgdesc = {desc}')
if url:
    info.append(f'url = {url}')
info += [f'builddate = {int(os.environ.get("SOURCE_DATE_EPOCH", time.time()))}',
         f'packager = mkapk.sh', f'size = {size}', f'arch = {arch}',
         f'origin = {name}']
if lic:
    info.append(f'license = {lic}')
for d in deps.split():
    info.append(f'depend = {d}')
info.append(f'datahash = {hashlib.sha256(data).hexdigest()}')
blob = ('\n'.join(info) + '\n').encode()


def put_pkginfo(tf):
    ti = tarfile.TarInfo('.PKGINFO')
    ti.size = len(blob)
    ti.mtime = 0
    ti.uname = ti.gname = 'root'
    tf.addfile(ti, io.BytesIO(blob))


with open(apkpath, 'wb') as f:
    f.write(segment(put_pkginfo, cut=True))
    f.write(data)
print(apkpath)
PY

echo "Unsigned; install it with: apk add --allow-untrusted $apk"
